name: Create File Release

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC every day
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Free disk space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main
        with:
          disable_annotations: true

      - name: Expose actions cache variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env['ACTIONS_CACHE_URL'])
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN'])

      - name: win-cross Cache
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 5
        id: cache-win-cross
        uses: useblacksmith/cache@v5
        with:
          path: ${HOME}/win-cross
          key: win-cross

      - name: Initialize dependencies and repository
        run: |
          ./ubuntu-windows/init.sh
          ./ubuntu-windows/patch.sh

      - name: Build
        run: |
          ./ubuntu-windows/build.sh
          echo "FILE_NAME=$(cat ./zen-browser/desktop/dist/package_name.txt)" >> $GITHUB_ENV
          echo "RELEASE_FILE=$(realpath ./zen-browser/desktop/dist/$FILE_NAME.zip)" >> $GITHUB_ENV
          cd ./zen-browser/desktop/ 
          echo "ZEN_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      
      - name: Generate release notes
        run: |
          cat > release_notes.md << 'EOL'
          > [!WARNING]
          > These builds have Sandbox disabled, use at your own risk.

          # Experimental build
          + Windows only, because I mostly have RAM issues on Windows.

          # What's changed?
          + Updated to Zen Browser commit [${{ env.ZEN_COMMIT }}](https://github.com/zen-browser/desktop/commit/${{ env.ZEN_COMMIT }})
          EOL
          
          echo "NOTES<<EOF" >> $GITHUB_ENV
          cat release_notes.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: zen-${{ env.ZEN_COMMIT }}-win32
          release_name: zen-${{ env.ZEN_COMMIT }}-win32
          body: ${{ env.NOTES }}
          draft: false
          prerelease: false
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: zen-browser/desktop/dist/*
          tag: zen-${{ env.ZEN_COMMIT }}-win32
          overwrite: true
          file_glob: true